package com.lmp.facturacion_module.model.enums;

public enum CondicionIVA {
    RESPONSABLE_INSCRIPTO,
    SUJETO_EXENTO,
    CONSUMIDOR_FINAL,
    RESPONSABLE_MONOTRIBUTO,
    SUJETO_NO_CATEGORIZADO,
    PROVEEDOR_DEL_EXTERIOR,
    CLIENTE_DEL_EXTERIOR,
    IVA_LIBERATO_LEY_NRO_19640,
    MONOTRIBUTO_SOCIAL,
    IVA_NO_ALCANZADO,
    MONOTRIBUTISTA_TRABAJADOR_INDEPENDIENTE_PROMOVIDO
}
